version: 2.1

jobs:
    develop_build:
        docker:
            - image: marzer/misc_cpp17_dev:latest
        steps:
            - checkout
            - run:
                name: Checking toml.hpp
                command: |
                    cd python && python3 ci_single_header_check.py
            - run:
                name: Pulling Catch2
                command: |
                    git submodule update --init --recursive extern/Catch2
            - run:
                name: Building with clang
                command: |
                    CXX=clang++-9 meson build-clang
                    cd build-clang && ninja -v -j 4
            - run:
                name: Building with gcc
                command: |
                    CXX=g++-9 meson build-gcc
                    cd build-gcc && ninja -v -j 4  
            - run:
                name: Running tests
                command: |
                    cd build-clang && ninja test && cd ../build-gcc && ninja test


    master_build:
        docker:
            - image: marzer/misc_cpp17_dev:latest
        steps:
            - checkout
            - run:
                name: Checking toml.hpp
                command: |
                    cd python && python3 ci_single_header_check.py
            - run:
                name: Pulling Catch2
                command: |
                    git submodule update --init --recursive extern/Catch2
            - run:
                name: Building with clang
                command: |
                    CXX=clang++-9 meson build-clang
                    cd build-clang && ninja -v -j 4
            - run:
                name: Building with gcc
                command: |
                    CXX=g++-9 meson build-gcc
                    cd build-gcc && ninja -v -j 4  
            - run:
                name: Running tests
                command: |
                    cd build-clang && ninja test && cd ../build-gcc && ninja test
            - run:
                name: Generating documentation
                command: |
                    git submodule update --init extern/mcss
                    cd python && python3 generate_documentation.py
            - persist_to_workspace:
                root: docs
                paths: html

    deploy_dox:
        docker:
            - image: node:8.10.0
        steps:
            - checkout
            - attach_workspace:
                at: docs
            - run:
                name: Disable jekyll builds
                command: |
                    touch docs/html/.nojekyll
            - run:
                name: Installing dependencies
                command: |
                    npm install -g --silent gh-pages
                    git config user.email "ci-build@tomlplusplus.com"
                    git config user.name "ci-build"
            - add_ssh_keys:
                fingerprints:
                    - "a6:63:c0:a5:89:cf:2d:03:e7:c9:88:5d:c0:8c:39:e0"
            - run:
                name: Deploy docs to gh-pages branch
                command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/html

workflows:
    version: 2
    build:
        jobs:
            - master_build:
                filters:
                    branches:
                        only: master
            - deploy_dox:
                requires:
                    - master_build

            - develop_build:
                filters:
                    branches:
                        ignore: master
